SELECT * FROM intern.customer;
update customer set salary=8500 where seq_id='103';
alter table customer add name varchar(45);
select *from customer where seq_id='101';
update customer set batch='c#' where seq_id='107';
select *from customer where salary between 3000 and 7000;
select *from customer where (age ='22') or (age='30');
select *from customer where (age >'21' and  age>'26');
alter table customer change column seq_id id int;
update customer set name='kavin'where id='110';
delete from customer where id='108';
rollback;
commit;
select * from customer where name like'%a';
select * from customer where name like'%n%';
insert into customer(id,batch,salary,date1,age,name)values(110,'springboot',10000,'2019-12-01',20,'monika');
insert into customer(id,batch,salary,date1,age,name)values(111,'springframework',15000,'2019-11-01',30,'john');
select distinct(batch) from customer;
select max(age) from customer;
select min(salary) from customer;
select count(id) from customer;
select sum(salary) from customer;
select avg(salary) from customer;
select * from customer where name like'_n_';
